# Generated by Django 3.1.1 on 2020-09-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='blocked',
            new_name='is_blocked',
        ),
    ]
