# Generated by Django 3.1.1 on 2020-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200902_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
