# Generated by Django 3.1.1 on 2020-09-02 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('SIGIN_UP', 'Sign Up'), ('BLOCK', 'Block'), ('UN_BLOCK', 'Un Block'), ('MESSAGE_SEND', 'Message Send'), ('LOGIN', 'Valid Login'), ('INVALID_LOGIN', 'Invalid Login')], max_length=64)),
                ('data', models.TextField(blank=True, null=True)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='affected_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
